"""add mentor_matches

Revision ID: 0a770729a94b
Revises: a8f1249514fa
Create Date: 2026-06-16 12:29:23.015564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a770729a94b'
down_revision: Union[str, Sequence[str], None] = 'a8f1249514fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('founder_user_id', sa.Integer(), nullable=False),
    sa.Column('mentor_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_admin_override', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['founder_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('founder_user_id', 'mentor_user_id', name='uq_founder_mentor')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mentor_matches')
    # ### end Alembic commands ###
